services:
  meili:
    image: getmeili/meilisearch:v1.36.0
    container_name: meili
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_ENV: development
      MEILI_MASTER_KEY: MASTER_KEY
    restart: unless-stopped
